/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Apr 22 21:54:45 2018. */

#include "controller.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t controller_movement_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, controller_movement, direction, direction, 0),
    PB_LAST_FIELD
};

const pb_field_t controller_button_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, controller_button, button_id, button_id, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, controller_button, value, button_id, 0),
    PB_LAST_FIELD
};

const pb_field_t controller_controller_msg_fields[3] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, controller_controller_msg, go, go, &controller_movement_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , UNION, controller_controller_msg, btn, btn, &controller_button_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(controller_controller_msg, msg.go) < 65536 && pb_membersize(controller_controller_msg, msg.btn) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_controller_movement_controller_button_controller_controller_msg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(controller_controller_msg, msg.go) < 256 && pb_membersize(controller_controller_msg, msg.btn) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_controller_movement_controller_button_controller_controller_msg)
#endif


/* @@protoc_insertion_point(eof) */
