# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller.proto',
  package='controller',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63ontroller.proto\x12\ncontroller\"\x1d\n\x08movement\x12\x11\n\tdirection\x18\x01 \x01(\x05\"*\n\x06\x62utton\x12\x11\n\tbutton_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"^\n\x0e\x63ontroller_msg\x12\"\n\x02go\x18\x01 \x01(\x0b\x32\x14.controller.movementH\x00\x12!\n\x03\x62tn\x18\x02 \x01(\x0b\x32\x12.controller.buttonH\x00\x42\x05\n\x03msgb\x06proto3')
)




_MOVEMENT = _descriptor.Descriptor(
  name='movement',
  full_name='controller.movement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='controller.movement.direction', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=61,
)


_BUTTON = _descriptor.Descriptor(
  name='button',
  full_name='controller.button',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button_id', full_name='controller.button.button_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='controller.button.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=105,
)


_CONTROLLER_MSG = _descriptor.Descriptor(
  name='controller_msg',
  full_name='controller.controller_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='go', full_name='controller.controller_msg.go', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='btn', full_name='controller.controller_msg.btn', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='controller.controller_msg.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=107,
  serialized_end=201,
)

_CONTROLLER_MSG.fields_by_name['go'].message_type = _MOVEMENT
_CONTROLLER_MSG.fields_by_name['btn'].message_type = _BUTTON
_CONTROLLER_MSG.oneofs_by_name['msg'].fields.append(
  _CONTROLLER_MSG.fields_by_name['go'])
_CONTROLLER_MSG.fields_by_name['go'].containing_oneof = _CONTROLLER_MSG.oneofs_by_name['msg']
_CONTROLLER_MSG.oneofs_by_name['msg'].fields.append(
  _CONTROLLER_MSG.fields_by_name['btn'])
_CONTROLLER_MSG.fields_by_name['btn'].containing_oneof = _CONTROLLER_MSG.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['movement'] = _MOVEMENT
DESCRIPTOR.message_types_by_name['button'] = _BUTTON
DESCRIPTOR.message_types_by_name['controller_msg'] = _CONTROLLER_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

movement = _reflection.GeneratedProtocolMessageType('movement', (_message.Message,), dict(
  DESCRIPTOR = _MOVEMENT,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:controller.movement)
  ))
_sym_db.RegisterMessage(movement)

button = _reflection.GeneratedProtocolMessageType('button', (_message.Message,), dict(
  DESCRIPTOR = _BUTTON,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:controller.button)
  ))
_sym_db.RegisterMessage(button)

controller_msg = _reflection.GeneratedProtocolMessageType('controller_msg', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLER_MSG,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:controller.controller_msg)
  ))
_sym_db.RegisterMessage(controller_msg)


# @@protoc_insertion_point(module_scope)
