/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Apr 22 21:54:45 2018. */

#include "emulator.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t emulator_battle_state_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, emulator_battle_state, player_status, player_status, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, emulator_battle_state, match_inProgress, player_status, 0),
    PB_LAST_FIELD
};

const pb_field_t emulator_attacks_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, emulator_attacks, trainer, trainer, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, emulator_attacks, move, trainer, 0),
    PB_LAST_FIELD
};

const pb_field_t emulator_emu_msg_fields[3] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, emulator_emu_msg, battle_ctl, battle_ctl, &emulator_battle_state_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , UNION, emulator_emu_msg, battle_move, battle_move, &emulator_attacks_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(emulator_emu_msg, msg.battle_ctl) < 65536 && pb_membersize(emulator_emu_msg, msg.battle_move) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_emulator_battle_state_emulator_attacks_emulator_emu_msg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(emulator_emu_msg, msg.battle_ctl) < 256 && pb_membersize(emulator_emu_msg, msg.battle_move) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_emulator_battle_state_emulator_attacks_emulator_emu_msg)
#endif


/* @@protoc_insertion_point(eof) */
