# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emulator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='emulator.proto',
  package='emulator',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x65mulator.proto\x12\x08\x65mulator\"?\n\x0c\x62\x61ttle_state\x12\x15\n\rplayer_status\x18\x01 \x01(\x08\x12\x18\n\x10match_inProgress\x18\x02 \x01(\r\"(\n\x07\x61ttacks\x12\x0f\n\x07trainer\x18\x01 \x01(\x08\x12\x0c\n\x04move\x18\x02 \x01(\r\"h\n\x07\x65mu_msg\x12,\n\nbattle_ctl\x18\x01 \x01(\x0b\x32\x16.emulator.battle_stateH\x00\x12(\n\x0b\x62\x61ttle_move\x18\x02 \x01(\x0b\x32\x11.emulator.attacksH\x00\x42\x05\n\x03msgb\x06proto3')
)




_BATTLE_STATE = _descriptor.Descriptor(
  name='battle_state',
  full_name='emulator.battle_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_status', full_name='emulator.battle_state.player_status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match_inProgress', full_name='emulator.battle_state.match_inProgress', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=91,
)


_ATTACKS = _descriptor.Descriptor(
  name='attacks',
  full_name='emulator.attacks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainer', full_name='emulator.attacks.trainer', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move', full_name='emulator.attacks.move', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=133,
)


_EMU_MSG = _descriptor.Descriptor(
  name='emu_msg',
  full_name='emulator.emu_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battle_ctl', full_name='emulator.emu_msg.battle_ctl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battle_move', full_name='emulator.emu_msg.battle_move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='emulator.emu_msg.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=135,
  serialized_end=239,
)

_EMU_MSG.fields_by_name['battle_ctl'].message_type = _BATTLE_STATE
_EMU_MSG.fields_by_name['battle_move'].message_type = _ATTACKS
_EMU_MSG.oneofs_by_name['msg'].fields.append(
  _EMU_MSG.fields_by_name['battle_ctl'])
_EMU_MSG.fields_by_name['battle_ctl'].containing_oneof = _EMU_MSG.oneofs_by_name['msg']
_EMU_MSG.oneofs_by_name['msg'].fields.append(
  _EMU_MSG.fields_by_name['battle_move'])
_EMU_MSG.fields_by_name['battle_move'].containing_oneof = _EMU_MSG.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['battle_state'] = _BATTLE_STATE
DESCRIPTOR.message_types_by_name['attacks'] = _ATTACKS
DESCRIPTOR.message_types_by_name['emu_msg'] = _EMU_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

battle_state = _reflection.GeneratedProtocolMessageType('battle_state', (_message.Message,), dict(
  DESCRIPTOR = _BATTLE_STATE,
  __module__ = 'emulator_pb2'
  # @@protoc_insertion_point(class_scope:emulator.battle_state)
  ))
_sym_db.RegisterMessage(battle_state)

attacks = _reflection.GeneratedProtocolMessageType('attacks', (_message.Message,), dict(
  DESCRIPTOR = _ATTACKS,
  __module__ = 'emulator_pb2'
  # @@protoc_insertion_point(class_scope:emulator.attacks)
  ))
_sym_db.RegisterMessage(attacks)

emu_msg = _reflection.GeneratedProtocolMessageType('emu_msg', (_message.Message,), dict(
  DESCRIPTOR = _EMU_MSG,
  __module__ = 'emulator_pb2'
  # @@protoc_insertion_point(class_scope:emulator.emu_msg)
  ))
_sym_db.RegisterMessage(emu_msg)


# @@protoc_insertion_point(module_scope)
