/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Apr 22 21:54:45 2018. */

#include "motor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t motor_motor_ctl_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, motor_motor_ctl, direction, direction, 0),
    PB_LAST_FIELD
};

const pb_field_t motor_motor_data_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, motor_motor_data, right_ticks, right_ticks, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, motor_motor_data, cur_dir, right_ticks, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, motor_motor_data, left_ticks, cur_dir, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, motor_motor_data, right_err, left_ticks, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, motor_motor_data, left_err, right_err, 0),
    PB_LAST_FIELD
};

const pb_field_t motor_motor_msg_fields[3] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, motor_motor_msg, ctl_msg, ctl_msg, &motor_motor_ctl_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , UNION, motor_motor_msg, data, data, &motor_motor_data_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(motor_motor_msg, msg.ctl_msg) < 65536 && pb_membersize(motor_motor_msg, msg.data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_motor_motor_ctl_motor_motor_data_motor_motor_msg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(motor_motor_msg, msg.ctl_msg) < 256 && pb_membersize(motor_motor_msg, msg.data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_motor_motor_ctl_motor_motor_data_motor_motor_msg)
#endif


/* @@protoc_insertion_point(eof) */
