# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motor.proto',
  package='motor',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmotor.proto\x12\x05motor\"\x1e\n\tmotor_ctl\x12\x11\n\tdirection\x18\x01 \x01(\r\"k\n\nmotor_data\x12\x13\n\x0bright_ticks\x18\x01 \x01(\r\x12\x0f\n\x07\x63ur_dir\x18\x02 \x01(\r\x12\x12\n\nleft_ticks\x18\x03 \x01(\r\x12\x11\n\tright_err\x18\x04 \x01(\r\x12\x10\n\x08left_err\x18\x05 \x01(\r\"Z\n\tmotor_msg\x12#\n\x07\x63tl_msg\x18\x01 \x01(\x0b\x32\x10.motor.motor_ctlH\x00\x12!\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x11.motor.motor_dataH\x00\x42\x05\n\x03msgb\x06proto3')
)




_MOTOR_CTL = _descriptor.Descriptor(
  name='motor_ctl',
  full_name='motor.motor_ctl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='motor.motor_ctl.direction', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_MOTOR_DATA = _descriptor.Descriptor(
  name='motor_data',
  full_name='motor.motor_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='right_ticks', full_name='motor.motor_data.right_ticks', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cur_dir', full_name='motor.motor_data.cur_dir', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_ticks', full_name='motor.motor_data.left_ticks', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_err', full_name='motor.motor_data.right_err', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_err', full_name='motor.motor_data.left_err', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=161,
)


_MOTOR_MSG = _descriptor.Descriptor(
  name='motor_msg',
  full_name='motor.motor_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctl_msg', full_name='motor.motor_msg.ctl_msg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='motor.motor_msg.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='motor.motor_msg.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=163,
  serialized_end=253,
)

_MOTOR_MSG.fields_by_name['ctl_msg'].message_type = _MOTOR_CTL
_MOTOR_MSG.fields_by_name['data'].message_type = _MOTOR_DATA
_MOTOR_MSG.oneofs_by_name['msg'].fields.append(
  _MOTOR_MSG.fields_by_name['ctl_msg'])
_MOTOR_MSG.fields_by_name['ctl_msg'].containing_oneof = _MOTOR_MSG.oneofs_by_name['msg']
_MOTOR_MSG.oneofs_by_name['msg'].fields.append(
  _MOTOR_MSG.fields_by_name['data'])
_MOTOR_MSG.fields_by_name['data'].containing_oneof = _MOTOR_MSG.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['motor_ctl'] = _MOTOR_CTL
DESCRIPTOR.message_types_by_name['motor_data'] = _MOTOR_DATA
DESCRIPTOR.message_types_by_name['motor_msg'] = _MOTOR_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

motor_ctl = _reflection.GeneratedProtocolMessageType('motor_ctl', (_message.Message,), dict(
  DESCRIPTOR = _MOTOR_CTL,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:motor.motor_ctl)
  ))
_sym_db.RegisterMessage(motor_ctl)

motor_data = _reflection.GeneratedProtocolMessageType('motor_data', (_message.Message,), dict(
  DESCRIPTOR = _MOTOR_DATA,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:motor.motor_data)
  ))
_sym_db.RegisterMessage(motor_data)

motor_msg = _reflection.GeneratedProtocolMessageType('motor_msg', (_message.Message,), dict(
  DESCRIPTOR = _MOTOR_MSG,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:motor.motor_msg)
  ))
_sym_db.RegisterMessage(motor_msg)


# @@protoc_insertion_point(module_scope)
