/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Apr 22 21:54:45 2018. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sensor_ir_sensor_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, sensor_ir_sensor, distance, distance, 0),
    PB_LAST_FIELD
};

const pb_field_t sensor_color_sensor_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, sensor_color_sensor, color_code, color_code, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, sensor_color_sensor, x, color_code, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, sensor_color_sensor, y, x, 0),
    PB_LAST_FIELD
};

const pb_field_t sensor_sensor_msg_fields[3] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, sensor_sensor_msg, dist_data, dist_data, &sensor_ir_sensor_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , UNION, sensor_sensor_msg, color_data, color_data, &sensor_color_sensor_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(sensor_sensor_msg, msg.dist_data) < 65536 && pb_membersize(sensor_sensor_msg, msg.color_data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_sensor_ir_sensor_sensor_color_sensor_sensor_sensor_msg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(sensor_sensor_msg, msg.dist_data) < 256 && pb_membersize(sensor_sensor_msg, msg.color_data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_sensor_ir_sensor_sensor_color_sensor_sensor_sensor_msg)
#endif


/* @@protoc_insertion_point(eof) */
