/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Apr 22 21:54:45 2018. */

#include "server.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t server_server_fields[13] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, server_server, sequence_number, sequence_number, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, server_server, uid, sequence_number, 0),
    PB_ONEOF_FIELD(payload,   3, MESSAGE , ONEOF, STATIC  , OTHER, server_server, color_data, uid, &sensor_color_sensor_fields),
    PB_ONEOF_FIELD(payload,   4, MESSAGE , ONEOF, STATIC  , UNION, server_server, ir_data, uid, &sensor_ir_sensor_fields),
    PB_ONEOF_FIELD(payload,   5, MESSAGE , ONEOF, STATIC  , UNION, server_server, mCmd, uid, &motor_motor_ctl_fields),
    PB_ONEOF_FIELD(payload,   6, MESSAGE , ONEOF, STATIC  , UNION, server_server, data, uid, &motor_motor_data_fields),
    PB_ONEOF_FIELD(payload,   7, MESSAGE , ONEOF, STATIC  , UNION, server_server, battle, uid, &emulator_battle_state_fields),
    PB_ONEOF_FIELD(payload,   8, MESSAGE , ONEOF, STATIC  , UNION, server_server, atk, uid, &emulator_attacks_fields),
    PB_ONEOF_FIELD(payload,   9, MESSAGE , ONEOF, STATIC  , UNION, server_server, again, uid, &status_request_resend_fields),
    PB_ONEOF_FIELD(payload,  10, MESSAGE , ONEOF, STATIC  , UNION, server_server, done, uid, &status_request_complete_fields),
    PB_ONEOF_FIELD(payload,  11, MESSAGE , ONEOF, STATIC  , UNION, server_server, health, uid, &status_device_status_fields),
    PB_ONEOF_FIELD(payload,  12, MESSAGE , ONEOF, STATIC  , UNION, server_server, ctl, uid, &controller_controller_msg_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(server_server, payload.color_data) < 65536 && pb_membersize(server_server, payload.ir_data) < 65536 && pb_membersize(server_server, payload.mCmd) < 65536 && pb_membersize(server_server, payload.data) < 65536 && pb_membersize(server_server, payload.battle) < 65536 && pb_membersize(server_server, payload.atk) < 65536 && pb_membersize(server_server, payload.again) < 65536 && pb_membersize(server_server, payload.done) < 65536 && pb_membersize(server_server, payload.health) < 65536 && pb_membersize(server_server, payload.ctl) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_server_server)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(server_server, payload.color_data) < 256 && pb_membersize(server_server, payload.ir_data) < 256 && pb_membersize(server_server, payload.mCmd) < 256 && pb_membersize(server_server, payload.data) < 256 && pb_membersize(server_server, payload.battle) < 256 && pb_membersize(server_server, payload.atk) < 256 && pb_membersize(server_server, payload.again) < 256 && pb_membersize(server_server, payload.done) < 256 && pb_membersize(server_server, payload.health) < 256 && pb_membersize(server_server, payload.ctl) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_server_server)
#endif


/* @@protoc_insertion_point(eof) */
