# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status.proto',
  package='status',
  syntax='proto3',
  serialized_pb=_b('\n\x0cstatus.proto\x12\x06status\"+\n\x10request_complete\x12\x17\n\x0fsequence_number\x18\x01 \x01(\r\")\n\x0erequest_resend\x12\x17\n\x0fsequence_number\x18\x01 \x01(\r\"v\n\rdevice_status\x12\x11\n\tserver_up\x18\x01 \x01(\x08\x12\x15\n\rcontroller_up\x18\x02 \x01(\x08\x12\x12\n\ntrainer_up\x18\x03 \x01(\x08\x12\x12\n\npikachu_up\x18\x04 \x01(\x08\x12\x13\n\x0b\x65mulator_up\x18\x05 \x01(\x08\"\x8e\x01\n\nstatus_msg\x12(\n\x04\x64one\x18\x01 \x01(\x0b\x32\x18.status.request_completeH\x00\x12\'\n\x05\x61gain\x18\x02 \x01(\x0b\x32\x16.status.request_resendH\x00\x12&\n\x05stats\x18\x03 \x01(\x0b\x32\x15.status.device_statusH\x00\x42\x05\n\x03msgb\x06proto3')
)




_REQUEST_COMPLETE = _descriptor.Descriptor(
  name='request_complete',
  full_name='status.request_complete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='status.request_complete.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)


_REQUEST_RESEND = _descriptor.Descriptor(
  name='request_resend',
  full_name='status.request_resend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='status.request_resend.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=110,
)


_DEVICE_STATUS = _descriptor.Descriptor(
  name='device_status',
  full_name='status.device_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_up', full_name='status.device_status.server_up', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_up', full_name='status.device_status.controller_up', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trainer_up', full_name='status.device_status.trainer_up', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pikachu_up', full_name='status.device_status.pikachu_up', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emulator_up', full_name='status.device_status.emulator_up', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=230,
)


_STATUS_MSG = _descriptor.Descriptor(
  name='status_msg',
  full_name='status.status_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='status.status_msg.done', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='again', full_name='status.status_msg.again', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='status.status_msg.stats', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='status.status_msg.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=233,
  serialized_end=375,
)

_STATUS_MSG.fields_by_name['done'].message_type = _REQUEST_COMPLETE
_STATUS_MSG.fields_by_name['again'].message_type = _REQUEST_RESEND
_STATUS_MSG.fields_by_name['stats'].message_type = _DEVICE_STATUS
_STATUS_MSG.oneofs_by_name['msg'].fields.append(
  _STATUS_MSG.fields_by_name['done'])
_STATUS_MSG.fields_by_name['done'].containing_oneof = _STATUS_MSG.oneofs_by_name['msg']
_STATUS_MSG.oneofs_by_name['msg'].fields.append(
  _STATUS_MSG.fields_by_name['again'])
_STATUS_MSG.fields_by_name['again'].containing_oneof = _STATUS_MSG.oneofs_by_name['msg']
_STATUS_MSG.oneofs_by_name['msg'].fields.append(
  _STATUS_MSG.fields_by_name['stats'])
_STATUS_MSG.fields_by_name['stats'].containing_oneof = _STATUS_MSG.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['request_complete'] = _REQUEST_COMPLETE
DESCRIPTOR.message_types_by_name['request_resend'] = _REQUEST_RESEND
DESCRIPTOR.message_types_by_name['device_status'] = _DEVICE_STATUS
DESCRIPTOR.message_types_by_name['status_msg'] = _STATUS_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request_complete = _reflection.GeneratedProtocolMessageType('request_complete', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_COMPLETE,
  __module__ = 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.request_complete)
  ))
_sym_db.RegisterMessage(request_complete)

request_resend = _reflection.GeneratedProtocolMessageType('request_resend', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_RESEND,
  __module__ = 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.request_resend)
  ))
_sym_db.RegisterMessage(request_resend)

device_status = _reflection.GeneratedProtocolMessageType('device_status', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE_STATUS,
  __module__ = 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.device_status)
  ))
_sym_db.RegisterMessage(device_status)

status_msg = _reflection.GeneratedProtocolMessageType('status_msg', (_message.Message,), dict(
  DESCRIPTOR = _STATUS_MSG,
  __module__ = 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.status_msg)
  ))
_sym_db.RegisterMessage(status_msg)


# @@protoc_insertion_point(module_scope)
