/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Apr 22 21:54:45 2018. */

#include "status.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t status_request_complete_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, status_request_complete, sequence_number, sequence_number, 0),
    PB_LAST_FIELD
};

const pb_field_t status_request_resend_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, status_request_resend, sequence_number, sequence_number, 0),
    PB_LAST_FIELD
};

const pb_field_t status_device_status_fields[6] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, status_device_status, server_up, server_up, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, status_device_status, controller_up, server_up, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, status_device_status, trainer_up, controller_up, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, status_device_status, pikachu_up, trainer_up, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, status_device_status, emulator_up, pikachu_up, 0),
    PB_LAST_FIELD
};

const pb_field_t status_status_msg_fields[4] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, status_status_msg, done, done, &status_request_complete_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , UNION, status_status_msg, again, again, &status_request_resend_fields),
    PB_ONEOF_FIELD(msg,   3, MESSAGE , ONEOF, STATIC  , UNION, status_status_msg, stats, stats, &status_device_status_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(status_status_msg, msg.done) < 65536 && pb_membersize(status_status_msg, msg.again) < 65536 && pb_membersize(status_status_msg, msg.stats) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_status_request_complete_status_request_resend_status_device_status_status_status_msg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(status_status_msg, msg.done) < 256 && pb_membersize(status_status_msg, msg.again) < 256 && pb_membersize(status_status_msg, msg.stats) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_status_request_complete_status_request_resend_status_device_status_status_status_msg)
#endif


/* @@protoc_insertion_point(eof) */
